# Site settings
title: Rivik Media
email: hello@rivikmedia.com
description: A Connectiucut base web development and technology consukting agency for small businesses. 
baseurl: "/" 
url: "http://rivik-media.github.io"
twitter_username: rivikmedia
github_username:  rivik-media

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# google_analytics: 

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
