# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rivik Media
email: hello@rivikmedia.com
description: A Connectiucut base web development and technology consukting agency for small businesses. 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://rivik-media.github.io" # the base hostname & protocol for your site
twitter_username: rivikmedia
github_username:  rivik-media

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
